import * as day1 from './day1';
import * as day2 from './day2';
import * as day3 from './day3';
import * as day4 from './day4';
import * as day5 from './day5';
import * as day6 from './day6';

console.log("--------------------- DAY 1 ---------------------");
console.log("Result for day 1 part 1", day1.result1);
console.log("Result for day 1 part 2", day1.result2);
console.log("--------------------- DAY 2 ---------------------");
console.log("Result for day 2 part 1", day2.result1);
console.log("Result for day 2 part 2", day2.result2);
console.log("--------------------- DAY 3 ---------------------");
console.log("Result for day 3 part 1", day3.result1);
console.log("Result for day 3 part 2", day3.result2);
console.log("--------------------- DAY 4 ---------------------");
console.log("Result for day 4 part 1", day4.result1);
console.log("Result for day 4 part 2", day4.result2);
console.log("--------------------- DAY 5 ---------------------");
console.log("Result for day 5 part 1", day5.result1);
console.log("Result for day 5 part 2", day5.result2);
console.log("--------------------- DAY 6 ---------------------");
console.log("Result for day 6 part 1", day6.result1);
console.log("Result for day 6 part 2", day6.result2);
console.log("--------------------- DAY 7 ---------------------");
